import { CHORD_VOICING_SELF_PACED_DRUM_LOOP_URL } from '@/utils/earTrainingChordVoicingDrumLoop';
import { DEFAULT_EAR_TRAINING_TUTORIAL_UI } from './earTrainingTutorialDefaults';
import type { EarTrainingTutorialScriptPayload } from './earTrainingTutorialScriptTypes';

const OSMD_MUSIC_XML =
  'https://jazzify-cdn.com/fantasy-bgm/ear-training-dev-chord-osmd-120-lesson7-whole.musicxml';
const OSMD_AUDIO =
  'https://jazzify-cdn.com/fantasy-bgm/ear-training-dev-chord-osmd-120-phrase-01.mp3';

/** 開発者コース全分岐テスト用台本 */
export const buildEarTrainingDeveloperFullV1Script = (): EarTrainingTutorialScriptPayload => ({
  version: 1,
  audioTracks: {
    drum_loop: { url: CHORD_VOICING_SELF_PACED_DRUM_LOOP_URL, volume: 0.35 },
  },
  ui: DEFAULT_EAR_TRAINING_TUTORIAL_UI,
  content: {
    'quiz-pool': {
      stage: {
        slug: 'tutorial-quiz-pool',
        title: 'チュートリアル・コードクイズ',
        title_en: 'Tutorial chord quiz',
        bpm: 100,
        key_fifths: 0,
        beats_per_measure: 4,
        beat_type: 4,
        loop_measures: 2,
        max_loops_per_phrase: 6,
        count_in_beats: 0,
        time_limit_sec: 180,
        player_hp: 100,
        enemy_hp: 10000,
        miss_damage: 0,
        fail_damage: 0,
        background_theme: 'blue_club',
        mode: 'chord_quiz',
        quiz_duration_seconds: 300,
        quiz_question_order: 'random',
        quiz_show_notation_in_battle: true,
        quiz_required_correct_count: 99,
        show_keyboard_hints_in_battle: true,
      },
      chord_quiz_items: [
        {
          order_index: 0,
          chord_name: 'CM7',
          voicing: ['C3', 'E3', 'G3', 'B3'],
          voicing_staves: [2, 2, 2, 2],
        },
        {
          order_index: 1,
          chord_name: 'Dm7',
          voicing: ['D3', 'F3', 'A3', 'C4'],
          voicing_staves: [2, 2, 2, 1],
        },
        {
          order_index: 2,
          chord_name: 'G7',
          voicing: ['G3', 'B3', 'D4', 'F4'],
          voicing_staves: [2, 2, 1, 1],
        },
      ],
    },
    'self-paced-ii-vi': {
      stage: {
        slug: 'tutorial-self-paced',
        title: 'チュートリアル・セルフペース',
        title_en: 'Tutorial self-paced',
        bpm: 120,
        key_fifths: 0,
        beats_per_measure: 4,
        beat_type: 4,
        loop_measures: 4,
        max_loops_per_phrase: 8,
        count_in_beats: 0,
        time_limit_sec: 300,
        player_hp: 100,
        enemy_hp: 10000,
        per_correct_note_damage: 5,
        good_completion_damage: 20,
        miss_damage: 0,
        fail_damage: 0,
        background_theme: 'blue_club',
        mode: 'chord_voicing',
        chord_voicing_self_paced: true,
        show_keyboard_hints_in_battle: true,
      },
      phrases: [
        {
          order_index: 0,
          title: 'II-V-I',
          loop_duration_sec: 8,
          chords: [
            {
              order_index: 0,
              chord_name: 'Dm7',
              measure_number: 1,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 0,
              end_time_sec: 2,
              voicing: ['D3', 'F3', 'A3', 'C4'],
              voicing_staves: [2, 2, 2, 1],
              quote: {
                ja: 'Dm7（II）。このヴォイシングをドラムに合わせて。',
                en: 'Dm7 (II). Play this voicing with the drums.',
              },
            },
            {
              order_index: 1,
              chord_name: 'G7',
              measure_number: 2,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 2,
              end_time_sec: 4,
              voicing: ['G3', 'B3', 'D4', 'F4'],
              voicing_staves: [2, 2, 1, 1],
              quote: {
                ja: 'G7（V）。次はこちらです。',
                en: 'G7 (V). Next chord.',
              },
            },
            {
              order_index: 2,
              chord_name: 'CM7',
              measure_number: 3,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 4,
              end_time_sec: 8,
              voicing: ['C3', 'E3', 'G3', 'B3'],
              voicing_staves: [2, 2, 2, 2],
              quote: {
                ja: 'CM7（I）。聴き分けて演奏しよう。',
                en: 'CM7 (I). Hear the voicing and play.',
              },
            },
          ],
        },
      ],
    },
    'osmd-lesson7': {
      stage: {
        slug: 'tutorial-osmd-l7',
        title: 'チュートリアル・OSMD',
        title_en: 'Tutorial OSMD',
        bpm: 120,
        key_fifths: 0,
        beats_per_measure: 4,
        beat_type: 4,
        loop_measures: 4,
        max_loops_per_phrase: 4,
        count_in_beats: 4,
        time_limit_sec: 300,
        player_hp: 100,
        enemy_hp: 10000,
        per_correct_note_damage: 10,
        good_completion_damage: 30,
        miss_damage: 0,
        fail_damage: 0,
        background_theme: 'blue_club',
        mode: 'chord_osmd',
        show_keyboard_hints_in_battle: true,
      },
      phrases: [
        {
          order_index: 0,
          title: 'Finale 全音符',
          music_xml_url: OSMD_MUSIC_XML,
          audio_url: OSMD_AUDIO,
          loop_duration_sec: 8,
          audio_duration_sec: 8,
          note_count: 4,
          chords: [
            {
              order_index: 0,
              chord_name: 'Dm7',
              measure_number: 1,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 0,
              end_time_sec: 2,
              voicing: ['D4'],
              voicing_staves: [1],
            },
            {
              order_index: 1,
              chord_name: 'G7',
              measure_number: 2,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 2,
              end_time_sec: 4,
              voicing: ['G4'],
              voicing_staves: [1],
            },
            {
              order_index: 2,
              chord_name: 'CM7',
              measure_number: 3,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 4,
              end_time_sec: 6,
              voicing: ['C4'],
              voicing_staves: [1],
            },
            {
              order_index: 3,
              chord_name: 'A7',
              measure_number: 4,
              beat_offset: 1,
              duration_beats: 4,
              start_time_sec: 6,
              end_time_sec: 8,
              voicing: ['A4'],
              voicing_staves: [1],
            },
          ],
        },
      ],
    },
  },
  scenes: [
    {
      type: 'dialogue_only',
      lines: [
        { ja: '耳コピバトル・チュートリアルへようこそ。', en: 'Welcome to the ear training battle tutorial.' },
        { ja: 'まずはセリフだけのシーンです。', en: 'This is a dialogue-only scene first.' },
        { ja: 'ドラムループが流れています。', en: 'A drum loop is playing.' },
      ],
      lineIntervalSeconds: 4,
    },
    {
      type: 'chord_quiz',
      contentRef: 'quiz-pool',
      order: 'progression',
      questionCount: 2,
      answerTimeoutSeconds: 8,
      dialogue: {
        onQuestion: { ja: '順番に出題します。8秒以内に演奏！', en: 'Questions in order. Play within 8 seconds!' },
        onCorrect: { ja: '正解！', en: 'Correct!' },
        onAutoAnswer: { ja: '時間切れ…自動回答です。', en: 'Time up — auto answer.' },
      },
    },
    {
      type: 'chord_quiz',
      contentRef: 'quiz-pool',
      order: 'random',
      questionCount: 1,
      answerTimeoutSeconds: 8,
      dialogue: {
        onQuestion: { ja: 'ランダム出題です。', en: 'Random question.' },
        onCorrect: { ja: 'ナイス！', en: 'Nice!' },
        onAutoAnswer: { ja: '自動回答で次へ。', en: 'Auto answer — moving on.' },
      },
    },
    {
      type: 'chord_voicing_self_paced',
      contentRef: 'self-paced-ii-vi',
      requiredSuccessfulLoops: 2,
      dialogue: {},
    },
    {
      type: 'chord_osmd',
      contentRef: 'osmd-lesson7',
      playMode: 'demo',
      requiredLoops: 2,
      timedLines: [
        {
          phase: 'count_in',
          loop: 0,
          beat: 2,
          text: { ja: 'デモ：カウントイン中のセリフ。', en: 'Demo: dialogue during count-in.' },
        },
        {
          at: { loop: 0, measure: 1, beat: 1 },
          text: { ja: 'デモ：1 小節目。', en: 'Demo: measure 1.' },
        },
        {
          at: { loop: 0, measure: 3, beat: 1 },
          text: { ja: 'デモ：3 小節目。', en: 'Demo: measure 3.' },
        },
      ],
    },
    {
      type: 'chord_osmd',
      contentRef: 'osmd-lesson7',
      playMode: 'self',
      requiredLoops: 1,
      timedLines: [
        {
          phase: 'count_in',
          loop: 0,
          beat: 1,
          text: { ja: 'セルフ：カウントイン。', en: 'Self: count-in.' },
        },
        {
          at: { loop: 0, measure: 2, beat: 1 },
          text: { ja: 'セルフ：2 小節目で演奏。', en: 'Self: play at measure 2.' },
        },
      ],
    },
    {
      type: 'dialogue_only',
      lines: [
        { ja: 'お疲れさま。最後まで見るとクリアです。', en: 'Well done. Finish to clear the lesson.' },
      ],
      lineIntervalSeconds: 4,
    },
    { type: 'finish' },
  ],
  finish: { showCta: true },
});
