import {
  INACTIVE_SCENARIO_OVERRIDES,
  TUTORIAL_BOOTSTRAP_OVERRIDES,
  type SurvivalScenarioOverrides,
} from '@/components/survival/scenario/survivalScenarioTypes';

export const TUTORIAL_OVERRIDE_PRESETS: Record<string, Partial<SurvivalScenarioOverrides>> = {
  bootstrap: TUTORIAL_BOOTSTRAP_OVERRIDES,
  inactive: INACTIVE_SCENARIO_OVERRIDES,
  scene1: {
    ...TUTORIAL_BOOTSTRAP_OVERRIDES,
    hideHud: false,
    hideStageTitle: true,
    hideTimerDisplay: true,
    hideKillCounter: true,
    hidePauseButton: true,
    hideHintBadge: true,
    hideStatusStrip: true,
    hidePlayerHpBar: true,
    hideStaff: true,
    hideChordSlots: true,
    hideChordPad: true,
    blockSlotEvaluation: true,
  },
  scene2: {
    ...TUTORIAL_BOOTSTRAP_OVERRIDES,
    hideHud: true,
    hideHintBadge: true,
    hideStaff: true,
    hideChordSlots: true,
    hideComboBadge: true,
    hideChordPad: false,
    blockChordPadInput: true,
    blockMidiGameInput: true,
    blockSlotEvaluation: true,
  },
  scene3: {
    ...TUTORIAL_BOOTSTRAP_OVERRIDES,
    hideHud: false,
    hideStageTitle: true,
    hideTimerDisplay: true,
    hideKillCounter: true,
    hidePauseButton: true,
    hideHintBadge: true,
    hideStatusStrip: true,
    hideStaff: true,
    hideChordSlots: true,
    hideChordPad: false,
    hideComboBadge: true,
    scenarioStaffClef: 1,
    hideStaffOnBSlotCompletion: true,
    useChordMidiNotesForHintHighlights: true,
    staffMode: 'progression',
    blockSlotEvaluation: false,
    blockChordPadInput: false,
    blockMidiGameInput: false,
  },
  scene4Cleanup: {
    hideHintBadge: true,
    hideChordSlots: true,
    hideStaff: true,
    scenarioStaffClef: 1,
    hideStaffOnBSlotCompletion: false,
    useChordMidiNotesForHintHighlights: false,
    blockSlotEvaluation: true,
    bChordCompletionAttackSlot: null,
    bChordCompletionUseSpecial: false,
    staffMode: 'hidden',
  },
  scene5: {
    ...TUTORIAL_BOOTSTRAP_OVERRIDES,
    hideHud: true,
    hideHintBadge: true,
    hideStaff: true,
    hideChordSlots: true,
    hideComboBadge: true,
    hideChordPad: false,
    blockSlotEvaluation: true,
    blockChordPadInput: false,
    blockMidiGameInput: true,
  },
};

export function resolveTutorialOverridePreset(
  preset: string,
): Partial<SurvivalScenarioOverrides> | undefined {
  return TUTORIAL_OVERRIDE_PRESETS[preset];
}
