INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-03-08'),
  'MT-03-08',
  'メジャー/マイナー混合（全ルート）その2',
  'Major/Minor mix (全ルート) · Part 2',
  '',
  '',
  5,
  32,
  5,
  'progression_random',
  '["C","D","E","F","G","A","B","Db","Eb","Gb","Ab","Bb","Cm","Dm","Em","Fm","Gm","Am","Bm","C#m","Ebm","F#m","Abm","Bbm"]'::jsonb,
  '[]'::jsonb,
  false,
  10,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  32,
  1,
  'lesson',
  false,
  false,
  4,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-01'),
  'MT-04-01',
  '長2度上（CDE）',
  'M2 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M2","direction":"up"},{"type":"interval","chord":"D","interval":"M2","direction":"up"},{"type":"interval","chord":"E","interval":"M2","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-02'),
  'MT-04-02',
  '長2度上（FGAB）',
  'M2 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M2","direction":"up"},{"type":"interval","chord":"G","interval":"M2","direction":"up"},{"type":"interval","chord":"A","interval":"M2","direction":"up"},{"type":"interval","chord":"B","interval":"M2","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-03'),
  'MT-04-03',
  '長2度上（黒鍵）',
  'M2 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M2","direction":"up"},{"type":"interval","chord":"Eb","interval":"M2","direction":"up"},{"type":"interval","chord":"Gb","interval":"M2","direction":"up"},{"type":"interval","chord":"Ab","interval":"M2","direction":"up"},{"type":"interval","chord":"Bb","interval":"M2","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-04'),
  'MT-04-04',
  '長3度上（CDE）',
  'M3 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M3","direction":"up"},{"type":"interval","chord":"D","interval":"M3","direction":"up"},{"type":"interval","chord":"E","interval":"M3","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-05'),
  'MT-04-05',
  '長3度上（FGAB）',
  'M3 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M3","direction":"up"},{"type":"interval","chord":"G","interval":"M3","direction":"up"},{"type":"interval","chord":"A","interval":"M3","direction":"up"},{"type":"interval","chord":"B","interval":"M3","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-06'),
  'MT-04-06',
  '長3度上（黒鍵）',
  'M3 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M3","direction":"up"},{"type":"interval","chord":"Eb","interval":"M3","direction":"up"},{"type":"interval","chord":"Gb","interval":"M3","direction":"up"},{"type":"interval","chord":"Ab","interval":"M3","direction":"up"},{"type":"interval","chord":"Bb","interval":"M3","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-07'),
  'MT-04-07',
  '完全4度上（CDE）',
  'P4 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"P4","direction":"up"},{"type":"interval","chord":"D","interval":"P4","direction":"up"},{"type":"interval","chord":"E","interval":"P4","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-08'),
  'MT-04-08',
  '完全4度上（FGAB）',
  'P4 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"P4","direction":"up"},{"type":"interval","chord":"G","interval":"P4","direction":"up"},{"type":"interval","chord":"A","interval":"P4","direction":"up"},{"type":"interval","chord":"B","interval":"P4","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-09'),
  'MT-04-09',
  '完全4度上（黒鍵）',
  'P4 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"P4","direction":"up"},{"type":"interval","chord":"Eb","interval":"P4","direction":"up"},{"type":"interval","chord":"Gb","interval":"P4","direction":"up"},{"type":"interval","chord":"Ab","interval":"P4","direction":"up"},{"type":"interval","chord":"Bb","interval":"P4","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-10'),
  'MT-04-10',
  '完全5度上（CDE）',
  'P5 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"P5","direction":"up"},{"type":"interval","chord":"D","interval":"P5","direction":"up"},{"type":"interval","chord":"E","interval":"P5","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-11'),
  'MT-04-11',
  '完全5度上（FGAB）',
  'P5 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"P5","direction":"up"},{"type":"interval","chord":"G","interval":"P5","direction":"up"},{"type":"interval","chord":"A","interval":"P5","direction":"up"},{"type":"interval","chord":"B","interval":"P5","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-12'),
  'MT-04-12',
  '完全5度上（黒鍵）',
  'P5 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"P5","direction":"up"},{"type":"interval","chord":"Eb","interval":"P5","direction":"up"},{"type":"interval","chord":"Gb","interval":"P5","direction":"up"},{"type":"interval","chord":"Ab","interval":"P5","direction":"up"},{"type":"interval","chord":"Bb","interval":"P5","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-13'),
  'MT-04-13',
  '長6度上（CDE）',
  'M6 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M6","direction":"up"},{"type":"interval","chord":"D","interval":"M6","direction":"up"},{"type":"interval","chord":"E","interval":"M6","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-14'),
  'MT-04-14',
  '長6度上（FGAB）',
  'M6 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M6","direction":"up"},{"type":"interval","chord":"G","interval":"M6","direction":"up"},{"type":"interval","chord":"A","interval":"M6","direction":"up"},{"type":"interval","chord":"B","interval":"M6","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-15'),
  'MT-04-15',
  '長6度上（黒鍵）',
  'M6 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M6","direction":"up"},{"type":"interval","chord":"Eb","interval":"M6","direction":"up"},{"type":"interval","chord":"Gb","interval":"M6","direction":"up"},{"type":"interval","chord":"Ab","interval":"M6","direction":"up"},{"type":"interval","chord":"Bb","interval":"M6","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-16'),
  'MT-04-16',
  '長7度上（CDE）',
  'M7 up (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M7","direction":"up"},{"type":"interval","chord":"D","interval":"M7","direction":"up"},{"type":"interval","chord":"E","interval":"M7","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-17'),
  'MT-04-17',
  '長7度上（FGAB）',
  'M7 up (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M7","direction":"up"},{"type":"interval","chord":"G","interval":"M7","direction":"up"},{"type":"interval","chord":"A","interval":"M7","direction":"up"},{"type":"interval","chord":"B","interval":"M7","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-04-18'),
  'MT-04-18',
  '長7度上（黒鍵）',
  'M7 up (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M7","direction":"up"},{"type":"interval","chord":"Eb","interval":"M7","direction":"up"},{"type":"interval","chord":"Gb","interval":"M7","direction":"up"},{"type":"interval","chord":"Ab","interval":"M7","direction":"up"},{"type":"interval","chord":"Bb","interval":"M7","direction":"up"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-01'),
  'MT-05-01',
  '長2度下（CDE）',
  'M2 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M2","direction":"down"},{"type":"interval","chord":"D","interval":"M2","direction":"down"},{"type":"interval","chord":"E","interval":"M2","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-02'),
  'MT-05-02',
  '長2度下（FGAB）',
  'M2 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M2","direction":"down"},{"type":"interval","chord":"G","interval":"M2","direction":"down"},{"type":"interval","chord":"A","interval":"M2","direction":"down"},{"type":"interval","chord":"B","interval":"M2","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-03'),
  'MT-05-03',
  '長2度下（黒鍵）',
  'M2 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M2","direction":"down"},{"type":"interval","chord":"Eb","interval":"M2","direction":"down"},{"type":"interval","chord":"Gb","interval":"M2","direction":"down"},{"type":"interval","chord":"Ab","interval":"M2","direction":"down"},{"type":"interval","chord":"Bb","interval":"M2","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-04'),
  'MT-05-04',
  '長3度下（CDE）',
  'M3 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M3","direction":"down"},{"type":"interval","chord":"D","interval":"M3","direction":"down"},{"type":"interval","chord":"E","interval":"M3","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);
