INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-05'),
  'MT-05-05',
  '長3度下（FGAB）',
  'M3 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M3","direction":"down"},{"type":"interval","chord":"G","interval":"M3","direction":"down"},{"type":"interval","chord":"A","interval":"M3","direction":"down"},{"type":"interval","chord":"B","interval":"M3","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-06'),
  'MT-05-06',
  '長3度下（黒鍵）',
  'M3 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M3","direction":"down"},{"type":"interval","chord":"Eb","interval":"M3","direction":"down"},{"type":"interval","chord":"Gb","interval":"M3","direction":"down"},{"type":"interval","chord":"Ab","interval":"M3","direction":"down"},{"type":"interval","chord":"Bb","interval":"M3","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-07'),
  'MT-05-07',
  '完全4度下（CDE）',
  'P4 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"P4","direction":"down"},{"type":"interval","chord":"D","interval":"P4","direction":"down"},{"type":"interval","chord":"E","interval":"P4","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-08'),
  'MT-05-08',
  '完全4度下（FGAB）',
  'P4 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"P4","direction":"down"},{"type":"interval","chord":"G","interval":"P4","direction":"down"},{"type":"interval","chord":"A","interval":"P4","direction":"down"},{"type":"interval","chord":"B","interval":"P4","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-09'),
  'MT-05-09',
  '完全4度下（黒鍵）',
  'P4 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"P4","direction":"down"},{"type":"interval","chord":"Eb","interval":"P4","direction":"down"},{"type":"interval","chord":"Gb","interval":"P4","direction":"down"},{"type":"interval","chord":"Ab","interval":"P4","direction":"down"},{"type":"interval","chord":"Bb","interval":"P4","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-10'),
  'MT-05-10',
  '完全5度下（CDE）',
  'P5 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"P5","direction":"down"},{"type":"interval","chord":"D","interval":"P5","direction":"down"},{"type":"interval","chord":"E","interval":"P5","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-11'),
  'MT-05-11',
  '完全5度下（FGAB）',
  'P5 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"P5","direction":"down"},{"type":"interval","chord":"G","interval":"P5","direction":"down"},{"type":"interval","chord":"A","interval":"P5","direction":"down"},{"type":"interval","chord":"B","interval":"P5","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-12'),
  'MT-05-12',
  '完全5度下（黒鍵）',
  'P5 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"P5","direction":"down"},{"type":"interval","chord":"Eb","interval":"P5","direction":"down"},{"type":"interval","chord":"Gb","interval":"P5","direction":"down"},{"type":"interval","chord":"Ab","interval":"P5","direction":"down"},{"type":"interval","chord":"Bb","interval":"P5","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-13'),
  'MT-05-13',
  '長6度下（CDE）',
  'M6 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M6","direction":"down"},{"type":"interval","chord":"D","interval":"M6","direction":"down"},{"type":"interval","chord":"E","interval":"M6","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-14'),
  'MT-05-14',
  '長6度下（FGAB）',
  'M6 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M6","direction":"down"},{"type":"interval","chord":"G","interval":"M6","direction":"down"},{"type":"interval","chord":"A","interval":"M6","direction":"down"},{"type":"interval","chord":"B","interval":"M6","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-15'),
  'MT-05-15',
  '長6度下（黒鍵）',
  'M6 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M6","direction":"down"},{"type":"interval","chord":"Eb","interval":"M6","direction":"down"},{"type":"interval","chord":"Gb","interval":"M6","direction":"down"},{"type":"interval","chord":"Ab","interval":"M6","direction":"down"},{"type":"interval","chord":"Bb","interval":"M6","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-16'),
  'MT-05-16',
  '長7度下（CDE）',
  'M7 down (CDE)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"C","interval":"M7","direction":"down"},{"type":"interval","chord":"D","interval":"M7","direction":"down"},{"type":"interval","chord":"E","interval":"M7","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-17'),
  'MT-05-17',
  '長7度下（FGAB）',
  'M7 down (FGAB)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"F","interval":"M7","direction":"down"},{"type":"interval","chord":"G","interval":"M7","direction":"down"},{"type":"interval","chord":"A","interval":"M7","direction":"down"},{"type":"interval","chord":"B","interval":"M7","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-05-18'),
  'MT-05-18',
  '長7度下（黒鍵）',
  'M7 down (黒鍵)',
  '',
  '',
  10,
  100,
  5,
  'single',
  '[{"type":"interval","chord":"Db","interval":"M7","direction":"down"},{"type":"interval","chord":"Eb","interval":"M7","direction":"down"},{"type":"interval","chord":"Gb","interval":"M7","direction":"down"},{"type":"interval","chord":"Ab","interval":"M7","direction":"down"},{"type":"interval","chord":"Bb","interval":"M7","direction":"down"}]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-06-01'),
  'MT-06-01',
  'メジャースケール（C–F–Bb）',
  'Major scale (C–F–Bb)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["C major","F major","Bb major"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-06-02'),
  'MT-06-02',
  'メジャースケール（D–G–A）',
  'Major scale (D–G–A)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["D major","G major","A major"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-06-03'),
  'MT-06-03',
  'メジャースケール（B–E–Gb）',
  'Major scale (B–E–Gb)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["B major","E major","Gb major"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-06-04'),
  'MT-06-04',
  'メジャースケール（Eb–Ab–Db）',
  'Major scale (Eb–Ab–Db)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["Eb major","Ab major","Db major"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-06-05'),
  'MT-06-05',
  'メジャースケール（12調すべて）',
  'Major scale (12調すべて)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["C major","Db major","D major","Eb major","E major","F major","Gb major","G major","Ab major","A major","Bb major","B major"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-07-01'),
  'MT-07-01',
  'ナチュラルマイナー（A–D–G）',
  'Natural minor (A–D–G)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["A natural_minor","D natural_minor","G natural_minor"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-07-02'),
  'MT-07-02',
  'ナチュラルマイナー（B–E–C#）',
  'Natural minor (B–E–C#)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["B natural_minor","E natural_minor","C# natural_minor"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-07-03'),
  'MT-07-03',
  'ナチュラルマイナー（G#–C#–Eb）',
  'Natural minor (G#–C#–Eb)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["G# natural_minor","C# natural_minor","Eb natural_minor"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);

INSERT INTO public.fantasy_stages (
  id, stage_number, name, name_en, description, description_en,
  max_hp, question_count, enemy_gauge_seconds, mode,
  allowed_chords, chord_progression, show_guide,
  enemy_count, enemy_hp, min_damage, max_damage,
  simultaneous_monster_count, play_root_on_correct, stage_tier,
  bpm, time_signature, measure_count, count_in_measures,
  usage_type, is_sheet_music_mode, is_auftakt,
  note_interval_beats,
  bgm_url, mp3_url
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'mtb-v2-stage-MT-07-04'),
  'MT-07-04',
  'ナチュラルマイナー（C–F–Bb）',
  'Natural minor (C–F–Bb)',
  '',
  '',
  10,
  100,
  6,
  'single',
  '["C natural_minor","F natural_minor","Bb natural_minor"]'::jsonb,
  '[]'::jsonb,
  false,
  30,
  100,
  25,
  40,
  1,
  true,
  'basic',
  108,
  4,
  8,
  0,
  'lesson',
  false,
  false,
  NULL,
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3',
  'https://jazzify-cdn.com/fantasy-bgm/7fd0cd0b-8bad-4807-b855-5930cbdcf934.mp3'
);
