/** 複合フレーズボス戦: ユーザー指定固定ダメージ（攻撃ステータス補正なし） */

export const COMPOSITE_PHRASE_NOTE_DAMAGE = 50;
export const COMPOSITE_PHRASE_MEASURE_RANGE_DAMAGE = 50;
export const COMPOSITE_PHRASE_FINISH_RANGE_DAMAGE_PRIMARY = 2000;
export const COMPOSITE_PHRASE_FINISH_RANGE_DAMAGE_REPEAT = 100;
