export {
  COMPOSITE_PHRASE_FINISH_RANGE_DAMAGE_PRIMARY,
  COMPOSITE_PHRASE_FINISH_RANGE_DAMAGE_REPEAT,
  COMPOSITE_PHRASE_MEASURE_RANGE_DAMAGE,
  COMPOSITE_PHRASE_NOTE_DAMAGE,
} from '@/utils/compositePhraseDamage';
