-- リズムモードのステージを追加

-- リズムモード（ランダムパターン）のステージ
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  chord_progression,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  monster_icon,
  bgm_url,
  mp3_url,
  bpm,
  measure_count,
  time_signature,
  count_in_measures,
  chord_progression_data
) VALUES (
  '5-1',
  'リズムの洞窟',
  'リズムに合わせてコードを演奏しよう！',
  10,
  5,
  10,
  1,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F"]',
  NULL,
  true,
  true,
  1,
  'fa-drum',
  '/demo-1.mp3',
  '/demo-1.mp3',
  120,
  8,
  4,
  1,
  NULL
);

-- リズムモード（コード進行パターン）のステージ
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  chord_progression,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  monster_icon,
  bgm_url,
  mp3_url,
  bpm,
  measure_count,
  time_signature,
  count_in_measures,
  chord_progression_data
) VALUES (
  '5-2',
  'コード進行の塔',
  '決められたコード進行に従って演奏しよう！',
  10,
  5,
  16,
  1,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F", "Dm"]',
  NULL,
  true,
  true,
  1,
  'fa-music',
  '/demo-1.mp3',
  '/demo-1.mp3',
  120,
  8,
  4,
  1,
  '{"chords": [{"beat": 1.0, "chord": "C", "measure": 1}, {"beat": 1.0, "chord": "G", "measure": 2}, {"beat": 1.0, "chord": "Am", "measure": 3}, {"beat": 1.0, "chord": "F", "measure": 4}, {"beat": 1.0, "chord": "C", "measure": 5}, {"beat": 1.0, "chord": "Am", "measure": 6}, {"beat": 1.0, "chord": "Dm", "measure": 7}, {"beat": 1.0, "chord": "G", "measure": 8}]}'
);

-- リズムモード（高速ランダム）のステージ
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  chord_progression,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  monster_icon,
  bgm_url,
  mp3_url,
  bpm,
  measure_count,
  time_signature,
  count_in_measures,
  chord_progression_data
) VALUES (
  '5-3',
  '高速リズムダンジョン',
  '速いテンポでリズムを刻め！',
  8,
  4,
  20,
  1,
  1,
  2,
  'rhythm',
  '["C", "G", "Am", "F", "Dm", "Em"]',
  NULL,
  true,
  false,
  1,
  'fa-bolt',
  '/demo-1.mp3',
  '/demo-1.mp3',
  140,
  8,
  4,
  1,
  NULL
);