-- Insert sample rhythm mode stages
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  bpm,
  measure_count,
  time_signature,
  count_in_measures,
  mp3_url,
  chord_progression_data
) VALUES 
-- Random pattern rhythm stage
(
  '4-1',
  'リズムの洞窟',
  'リズムに合わせてコードを演奏しよう！',
  5,
  4.0,
  1,
  10,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F"]'::jsonb,
  true,
  true,
  1,
  120,
  8,
  4,
  1,
  '/demo-1.mp3',
  NULL
),
-- Chord progression rhythm stage
(
  '4-2',
  'ハーモニーの森',
  'コード進行に合わせて演奏しよう！',
  5,
  4.0,
  1,
  15,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F", "Dm"]'::jsonb,
  true,
  true,
  1,
  120,
  8,
  4,
  1,
  '/demo-1.mp3',
  '{"chords": [
    {"measure": 1, "beat": 1.0, "chord": "C"},
    {"measure": 2, "beat": 1.0, "chord": "G"},
    {"measure": 3, "beat": 1.0, "chord": "Am"},
    {"measure": 4, "beat": 1.0, "chord": "F"},
    {"measure": 5, "beat": 1.0, "chord": "C"},
    {"measure": 6, "beat": 1.0, "chord": "Am"},
    {"measure": 7, "beat": 1.0, "chord": "Dm"},
    {"measure": 8, "beat": 1.0, "chord": "G"}
  ]}'::jsonb
);