-- リズムモードのテストデータを挿入

-- リズムモード（ランダムパターン）のステージを挿入
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  monster_icon,
  bgm_url,
  measure_count,
  bpm,
  mp3_url,
  time_signature,
  count_in_measures,
  chord_progression_data
) VALUES (
  '4-1',
  'リズムの洞窟',
  'リズムに合わせてコードを演奏しよう！',
  5,
  4,
  10,
  1,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F"]'::jsonb,
  true,
  true,
  1,
  'fa-drum',
  NULL,
  8,
  120,
  '/demo-1.mp3',
  4,
  1,
  NULL
);

-- リズムモード（コード進行パターン）のステージを挿入
INSERT INTO fantasy_stages (
  stage_number,
  name,
  description,
  max_hp,
  enemy_gauge_seconds,
  enemy_count,
  enemy_hp,
  min_damage,
  max_damage,
  mode,
  allowed_chords,
  show_sheet_music,
  show_guide,
  simultaneous_monster_count,
  monster_icon,
  bgm_url,
  measure_count,
  bpm,
  mp3_url,
  time_signature,
  count_in_measures,
  chord_progression_data
) VALUES (
  '4-2',
  'ハーモニーの神殿',
  'コード進行に従って正確に演奏しよう！',
  5,
  4,
  15,
  1,
  1,
  1,
  'rhythm',
  '["C", "G", "Am", "F", "Dm"]'::jsonb,
  true,
  true,
  1,
  'fa-music',
  NULL,
  8,
  100,
  '/demo-1.mp3',
  4,
  1,
  '{"chords": [{"beat": 1.0, "chord": "C", "measure": 1}, {"beat": 1.0, "chord": "G", "measure": 2}, {"beat": 1.0, "chord": "Am", "measure": 3}, {"beat": 1.0, "chord": "F", "measure": 4}, {"beat": 1.0, "chord": "C", "measure": 5}, {"beat": 1.0, "chord": "Am", "measure": 6}, {"beat": 1.0, "chord": "Dm", "measure": 7}, {"beat": 1.0, "chord": "G", "measure": 8}]}'::jsonb
);