-- 既存の NULL / 空の lesson_songs.title_en を、title ごとの英語表記で埋める
UPDATE public.lesson_songs AS ls
SET title_en = v.en
FROM (VALUES
  ('FGAB クイズ'::text, 'FGAB quiz'::text),
  ('FGAB リズム'::text, 'FGAB rhythm'::text),
  ('ドミナントセブンス（CDE）その1'::text, 'Dominant 7th (CDE) Part 1'::text),
  ('ドミナントセブンス（CDE）その2'::text, 'Dominant 7th (CDE) Part 2'::text),
  ('ドミナントセブンス（FGAB）その1'::text, 'Dominant 7th (FGAB) Part 1'::text),
  ('ドミナントセブンス（FGAB）その2'::text, 'Dominant 7th (FGAB) Part 2'::text),
  ('ドミナントセブンス（全ルート）その1'::text, 'Dominant 7th (all roots) Part 1'::text),
  ('ドミナントセブンス（全ルート）その2'::text, 'Dominant 7th (all roots) Part 2'::text),
  ('ドミナントセブンス（黒鍵）その1'::text, 'Dominant 7th (black keys) Part 1'::text),
  ('ドミナントセブンス（黒鍵）その2'::text, 'Dominant 7th (black keys) Part 2'::text),
  ('ドレミファ川'::text, 'Do–Re–Mi–Fa river'::text),
  ('ナチュラルマイナー（12調すべて）'::text, 'Natural minor (all 12 keys)'::text),
  ('ナチュラルマイナー（A–D–G）'::text, 'Natural minor (A–D–G)'::text),
  ('ナチュラルマイナー（B–E–C#）'::text, 'Natural minor (B–E–C#)'::text),
  ('ナチュラルマイナー（C–F–Bb）'::text, 'Natural minor (C–F–Bb)'::text),
  ('ナチュラルマイナー（G#–C#–Eb）'::text, 'Natural minor (G#–C#–Eb)'::text),
  ('ハーフディミニッシュ（CDE）その1'::text, 'Half-diminished (CDE) Part 1'::text),
  ('ハーフディミニッシュ（CDE）その2'::text, 'Half-diminished (CDE) Part 2'::text),
  ('ハーフディミニッシュ（C#–Eb–F#–Ab–Bb）その1'::text, 'Half-diminished (C#–Eb–F#–Ab–Bb) Part 1'::text),
  ('ハーフディミニッシュ（C#–Eb–F#–Ab–Bb）その2'::text, 'Half-diminished (C#–Eb–F#–Ab–Bb) Part 2'::text),
  ('ハーフディミニッシュ（FGAB）その1'::text, 'Half-diminished (FGAB) Part 1'::text),
  ('ハーフディミニッシュ（FGAB）その2'::text, 'Half-diminished (FGAB) Part 2'::text),
  ('ハーフディミニッシュ（全ルート）その1'::text, 'Half-diminished (all roots) Part 1'::text),
  ('ハーフディミニッシュ（全ルート）その2'::text, 'Half-diminished (all roots) Part 2'::text),
  ('ハーモニックマイナー（12調すべて）'::text, 'Harmonic minor (all 12 keys)'::text),
  ('ハーモニックマイナー（A–D–G）'::text, 'Harmonic minor (A–D–G)'::text),
  ('ハーモニックマイナー（B–E–C#）'::text, 'Harmonic minor (B–E–C#)'::text),
  ('ハーモニックマイナー（C–F–Bb）'::text, 'Harmonic minor (C–F–Bb)'::text),
  ('ハーモニックマイナー（G#–C#–Eb）'::text, 'Harmonic minor (G#–C#–Eb)'::text),
  ('マイナーセブンス（CDE）その1'::text, 'Minor 7th (CDE) Part 1'::text),
  ('マイナーセブンス（CDE）その2'::text, 'Minor 7th (CDE) Part 2'::text),
  ('マイナーセブンス（C#–Eb–F#–Ab–Bb）その1'::text, 'Minor 7th (C#–Eb–F#–Ab–Bb) Part 1'::text),
  ('マイナーセブンス（C#–Eb–F#–Ab–Bb）その2'::text, 'Minor 7th (C#–Eb–F#–Ab–Bb) Part 2'::text),
  ('マイナーセブンス（FGAB）その1'::text, 'Minor 7th (FGAB) Part 1'::text),
  ('マイナーセブンス（FGAB）その2'::text, 'Minor 7th (FGAB) Part 2'::text),
  ('マイナーセブンス（全ルート）その1'::text, 'Minor 7th (all roots) Part 1'::text),
  ('マイナーセブンス（全ルート）その2'::text, 'Minor 7th (all roots) Part 2'::text),
  ('マイナートライアド（CDE）その1'::text, 'Minor triad (CDE) Part 1'::text),
  ('マイナートライアド（CDE）その2'::text, 'Minor triad (CDE) Part 2'::text),
  ('マイナートライアド（C#–Eb–F#–Ab–Bb）その1'::text, 'Minor triad (C#–Eb–F#–Ab–Bb) Part 1'::text),
  ('マイナートライアド（C#–Eb–F#–Ab–Bb）その2'::text, 'Minor triad (C#–Eb–F#–Ab–Bb) Part 2'::text),
  ('マイナートライアド（FGAB）その1'::text, 'Minor triad (FGAB) Part 1'::text),
  ('マイナートライアド（FGAB）その2'::text, 'Minor triad (FGAB) Part 2'::text),
  ('マイナートライアド（全ルート）その1'::text, 'Minor triad (all roots) Part 1'::text),
  ('マイナートライアド（全ルート）その2'::text, 'Minor triad (all roots) Part 2'::text),
  ('メジャースケール（12調すべて）'::text, 'Major scale (all 12 keys)'::text),
  ('メジャースケール（B–E–Gb）'::text, 'Major scale (B–E–Gb)'::text),
  ('メジャースケール（C–F–Bb）'::text, 'Major scale (C–F–Bb)'::text),
  ('メジャースケール（D–G–A）'::text, 'Major scale (D–G–A)'::text),
  ('メジャースケール（Eb–Ab–Db）'::text, 'Major scale (Eb–Ab–Db)'::text),
  ('メジャーセブンス（CDE）その1'::text, 'Major 7th (CDE) Part 1'::text),
  ('メジャーセブンス（CDE）その2'::text, 'Major 7th (CDE) Part 2'::text),
  ('メジャーセブンス（FGAB）その1'::text, 'Major 7th (FGAB) Part 1'::text),
  ('メジャーセブンス（FGAB）その2'::text, 'Major 7th (FGAB) Part 2'::text),
  ('メジャーセブンス（全ルート）その1'::text, 'Major 7th (all roots) Part 1'::text),
  ('メジャーセブンス（全ルート）その2'::text, 'Major 7th (all roots) Part 2'::text),
  ('メジャーセブンス（黒鍵）その1'::text, 'Major 7th (black keys) Part 1'::text),
  ('メジャーセブンス（黒鍵）その2'::text, 'Major 7th (black keys) Part 2'::text),
  ('メジャートライアド（CDE）その1'::text, 'Major triad (CDE) Part 1'::text),
  ('メジャートライアド（CDE）その2'::text, 'Major triad (CDE) Part 2'::text),
  ('メジャートライアド（FGAB）その1'::text, 'Major triad (FGAB) Part 1'::text),
  ('メジャートライアド（FGAB）その2'::text, 'Major triad (FGAB) Part 2'::text),
  ('メジャートライアド（全ルート）その1'::text, 'Major triad (all roots) Part 1'::text),
  ('メジャートライアド（全ルート）その2'::text, 'Major triad (all roots) Part 2'::text),
  ('メジャートライアド（黒鍵）その1'::text, 'Major triad (black keys) Part 1'::text),
  ('メジャートライアド（黒鍵）その2'::text, 'Major triad (black keys) Part 2'::text),
  ('メジャー/マイナー混合（CDE）その1'::text, 'Major/minor mix (CDE) Part 1'::text),
  ('メジャー/マイナー混合（CDE）その2'::text, 'Major/minor mix (CDE) Part 2'::text),
  ('メジャー/マイナー混合（FGAB）その1'::text, 'Major/minor mix (FGAB) Part 1'::text),
  ('メジャー/マイナー混合（FGAB）その2'::text, 'Major/minor mix (FGAB) Part 2'::text),
  ('メジャー/マイナー混合（全ルート）その1'::text, 'Major/minor mix (all roots) Part 1'::text),
  ('メジャー/マイナー混合（全ルート）その2'::text, 'Major/minor mix (all roots) Part 2'::text),
  ('メジャー/マイナー混合（黒鍵混合）その1'::text, 'Major/minor mix (black keys) Part 1'::text),
  ('メジャー/マイナー混合（黒鍵混合）その2'::text, 'Major/minor mix (black keys) Part 2'::text),
  ('♭ルート クイズ'::text, '♭ root quiz'::text),
  ('♯ルート クイズ'::text, '♯ root quiz'::text),
  ('♭ルート リズム'::text, '♭ root rhythm'::text),
  ('♯ルート リズム'::text, '♯ root rhythm'::text),
  ('♭ルート 順番'::text, '♭ root order'::text),
  ('♯ルート 順番'::text, '♯ root order'::text),
  ('両手 ABセクション'::text, 'Both hands: AB section'::text),
  ('両手 Aセクション'::text, 'Both hands: A section'::text),
  ('両手 BCセクション'::text, 'Both hands: BC section'::text),
  ('両手 Bセクション'::text, 'Both hands: B section'::text),
  ('両手 Cセクション'::text, 'Both hands: C section'::text),
  ('両手 通し'::text, 'Both hands: full piece'::text),
  ('全ルートクイズ'::text, 'All roots quiz'::text),
  ('半音での上昇下降 リズム'::text, 'Chromatic up/down: rhythm'::text),
  ('半音での上昇下降 順番'::text, 'Chromatic up/down: order'::text),
  ('右手 ABセクション'::text, 'Right hand: AB section'::text),
  ('右手 Aセクション'::text, 'Right hand: A section'::text),
  ('右手 BCセクション'::text, 'Right hand: BC section'::text),
  ('右手 Bセクション'::text, 'Right hand: B section'::text),
  ('右手 Cセクション'::text, 'Right hand: C section'::text),
  ('右手 通し'::text, 'Right hand: full piece'::text),
  ('基本4和音まとめ（CDE）その1'::text, 'Four basic chords (CDE) Part 1'::text),
  ('基本4和音まとめ（CDE）その2'::text, 'Four basic chords (CDE) Part 2'::text),
  ('基本4和音まとめ（C#–Eb–F#–Ab–Bb）その1'::text, 'Four basic chords (C#–Eb–F#–Ab–Bb) Part 1'::text),
  ('基本4和音まとめ（C#–Eb–F#–Ab–Bb）その2'::text, 'Four basic chords (C#–Eb–F#–Ab–Bb) Part 2'::text),
  ('基本4和音まとめ（FGAB）その1'::text, 'Four basic chords (FGAB) Part 1'::text),
  ('基本4和音まとめ（FGAB）その2'::text, 'Four basic chords (FGAB) Part 2'::text),
  ('基本4和音まとめ（全ルート）その1'::text, 'Four basic chords (all roots) Part 1'::text),
  ('基本4和音まとめ（全ルート）その2'::text, 'Four basic chords (all roots) Part 2'::text),
  ('始まりの丘'::text, 'Starting hill'::text),
  ('完全4度上（CDE）'::text, 'Perfect 4th up (CDE)'::text),
  ('完全4度上（FGAB）'::text, 'Perfect 4th up (FGAB)'::text),
  ('完全4度上（黒鍵）'::text, 'Perfect 4th up (black keys)'::text),
  ('完全4度下（CDE）'::text, 'Perfect 4th down (CDE)'::text),
  ('完全4度下（FGAB）'::text, 'Perfect 4th down (FGAB)'::text),
  ('完全4度下（黒鍵）'::text, 'Perfect 4th down (black keys)'::text),
  ('完全5度上（CDE）'::text, 'Perfect 5th up (CDE)'::text),
  ('完全5度上（FGAB）'::text, 'Perfect 5th up (FGAB)'::text),
  ('完全5度上（黒鍵）'::text, 'Perfect 5th up (black keys)'::text),
  ('完全5度下（CDE）'::text, 'Perfect 5th down (CDE)'::text),
  ('完全5度下（FGAB）'::text, 'Perfect 5th down (FGAB)'::text),
  ('完全5度下（黒鍵）'::text, 'Perfect 5th down (black keys)'::text),
  ('左手 ABセクション'::text, 'Left hand: AB section'::text),
  ('左手 Aセクション'::text, 'Left hand: A section'::text),
  ('左手 BCセクション'::text, 'Left hand: BC section'::text),
  ('左手 Bセクション'::text, 'Left hand: B section'::text),
  ('左手 Cセクション'::text, 'Left hand: C section'::text),
  ('左手 通し'::text, 'Left hand: full piece'::text),
  ('白鍵 リズム'::text, 'White keys: rhythm'::text),
  ('白鍵 順番'::text, 'White keys: order'::text),
  ('長2度上（CDE）'::text, 'Major 2nd up (CDE)'::text),
  ('長2度上（FGAB）'::text, 'Major 2nd up (FGAB)'::text),
  ('長2度上（黒鍵）'::text, 'Major 2nd up (black keys)'::text),
  ('長2度下（CDE）'::text, 'Major 2nd down (CDE)'::text),
  ('長2度下（FGAB）'::text, 'Major 2nd down (FGAB)'::text),
  ('長2度下（黒鍵）'::text, 'Major 2nd down (black keys)'::text),
  ('長3度上（CDE）'::text, 'Major 3rd up (CDE)'::text),
  ('長3度上（FGAB）'::text, 'Major 3rd up (FGAB)'::text),
  ('長3度上（黒鍵）'::text, 'Major 3rd up (black keys)'::text),
  ('長3度下（CDE）'::text, 'Major 3rd down (CDE)'::text),
  ('長3度下（FGAB）'::text, 'Major 3rd down (FGAB)'::text),
  ('長3度下（黒鍵）'::text, 'Major 3rd down (black keys)'::text),
  ('長6度上（CDE）'::text, 'Major 6th up (CDE)'::text),
  ('長6度上（FGAB）'::text, 'Major 6th up (FGAB)'::text),
  ('長6度上（黒鍵）'::text, 'Major 6th up (black keys)'::text),
  ('長6度下（CDE）'::text, 'Major 6th down (CDE)'::text),
  ('長6度下（FGAB）'::text, 'Major 6th down (FGAB)'::text),
  ('長6度下（黒鍵）'::text, 'Major 6th down (black keys)'::text),
  ('長7度上（CDE）'::text, 'Major 7th up (CDE)'::text),
  ('長7度上（FGAB）'::text, 'Major 7th up (FGAB)'::text),
  ('長7度上（黒鍵）'::text, 'Major 7th up (black keys)'::text),
  ('長7度下（CDE）'::text, 'Major 7th down (CDE)'::text),
  ('長7度下（FGAB）'::text, 'Major 7th down (FGAB)'::text),
  ('長7度下（黒鍵）'::text, 'Major 7th down (black keys)'::text),
  ('黒鍵クイズ'::text, 'Black keys quiz'::text)
) AS v(ja, en)
WHERE ls.title = v.ja AND (ls.title_en IS NULL OR btrim(ls.title_en) = '');

-- II-V-I フレーズコース（英語はパターン変換）
UPDATE public.lesson_songs
SET title_en = regexp_replace(
  regexp_replace(regexp_replace(title, 'II-V-I フレーズ', 'II-V-I phrases', 'g'), '（', '(', 'g'),
  '）', ')', 'g'
)
WHERE title LIKE 'II-V-I フレーズ%'
  AND (title_en IS NULL OR btrim(title_en) = '');

-- サバイバル等の共通ラベル
UPDATE public.lesson_songs SET title_en = 'CDE order' WHERE title = 'CDE 順番' AND (title_en IS NULL OR btrim(title_en) = '');
UPDATE public.lesson_songs SET title_en = 'CDE rhythm' WHERE title = 'CDE リズム' AND (title_en IS NULL OR btrim(title_en) = '');
UPDATE public.lesson_songs SET title_en = 'CDE quiz' WHERE title = 'CDE クイズ' AND (title_en IS NULL OR btrim(title_en) = '');
UPDATE public.lesson_songs SET title_en = 'FGAB order' WHERE title = 'FGAB 順番' AND (title_en IS NULL OR btrim(title_en) = '');
UPDATE public.lesson_songs SET title_en = 'All keys quiz' WHERE title = '全キークイズ' AND (title_en IS NULL OR btrim(title_en) = '');
UPDATE public.lesson_songs SET title_en = 'White keys quiz' WHERE title = '白鍵クイズ' AND (title_en IS NULL OR btrim(title_en) = '');
