-- Training mode: note reading 4 variants (generated by scripts/generate-training-seed.mjs)
-- treble/bass naturals + accidentals; bass In C fixed via bass_concert
BEGIN;

INSERT INTO public.trainings (
  id,
  category_id,
  slug,
  title_ja,
  title_en,
  sort_order,
  kind,
  clef_mode,
  use_key_signature,
  play_root_on_correct,
  bgm_url,
  config,
  is_active
) VALUES
  (uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-note-reading-treble'), uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-category-intro'), 'note-reading-treble', '音符の読み方(ト音記号)', 'Note Reading (Treble)', 1, 'note_reading', 'instrument', false, true, 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', '{"clef":"auto","include_accidentals":false}'::jsonb, true),
  (uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-note-reading-bass'), uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-category-intro'), 'note-reading-bass', '音符の読み方(ヘ音記号・In C固定)', 'Note Reading (Bass, In C)', 2, 'note_reading', 'bass_concert', false, true, 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', '{"clef":"bass","include_accidentals":false}'::jsonb, true),
  (uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-note-reading-treble-accidentals'), uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-category-intro'), 'note-reading-treble-accidentals', '音符の読み方(ト音記号・シャープフラットあり)', 'Note Reading (Treble, Accidentals)', 3, 'note_reading', 'instrument', false, true, 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', '{"clef":"auto","include_accidentals":true}'::jsonb, true),
  (uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-note-reading-bass-accidentals'), uuid_generate_v5('b0000000-0000-4000-8000-000000000001'::uuid, 'training-category-intro'), 'note-reading-bass-accidentals', '音符の読み方(ヘ音記号・シャープフラットあり・In C固定)', 'Note Reading (Bass, Accidentals, In C)', 4, 'note_reading', 'bass_concert', false, true, 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', '{"clef":"bass","include_accidentals":true}'::jsonb, true)
ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  title_ja = EXCLUDED.title_ja,
  title_en = EXCLUDED.title_en,
  sort_order = EXCLUDED.sort_order,
  kind = EXCLUDED.kind,
  clef_mode = EXCLUDED.clef_mode,
  use_key_signature = EXCLUDED.use_key_signature,
  play_root_on_correct = EXCLUDED.play_root_on_correct,
  bgm_url = EXCLUDED.bgm_url,
  config = EXCLUDED.config,
  is_active = EXCLUDED.is_active,
  updated_at = now();

COMMIT;
