-- Billing history tables (Lemon Phase 1). Entitlement remains on subscriptions.

CREATE TABLE public.billing_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('lemon')),
  provider_customer_id text NOT NULL,
  provider_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_customer_id)
);

CREATE INDEX billing_customers_user_provider_idx
  ON public.billing_customers (user_id, provider);

CREATE TABLE public.billing_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  billing_customer_id bigint REFERENCES public.billing_customers(id) ON DELETE SET NULL,
  provider text NOT NULL CHECK (provider IN ('lemon')),
  provider_subscription_id text NOT NULL,
  provider_customer_id text,
  provider_product_id text,
  provider_variant_id text,
  plan_code text,
  status text,
  renews_at timestamptz,
  ends_at timestamptz,
  cancelled_at timestamptz,
  provider_created_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_subscription_id)
);

CREATE INDEX billing_subscriptions_user_created_idx
  ON public.billing_subscriptions (user_id, provider_created_at DESC);

CREATE INDEX billing_subscriptions_provider_customer_idx
  ON public.billing_subscriptions (provider, provider_customer_id);

CREATE TABLE public.billing_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  billing_customer_id bigint REFERENCES public.billing_customers(id) ON DELETE SET NULL,
  billing_subscription_id bigint REFERENCES public.billing_subscriptions(id) ON DELETE SET NULL,
  provider text NOT NULL CHECK (provider IN ('lemon')),
  provider_invoice_id text NOT NULL,
  provider_subscription_id text NOT NULL,
  provider_customer_id text NOT NULL,
  billing_reason text,
  status text,
  currency text,
  total integer,
  subtotal integer,
  tax integer,
  refunded_amount integer,
  invoice_url text,
  paid_at timestamptz,
  provider_created_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_invoice_id)
);

CREATE INDEX billing_invoices_user_created_idx
  ON public.billing_invoices (user_id, provider_created_at DESC);

CREATE INDEX billing_invoices_provider_subscription_idx
  ON public.billing_invoices (provider, provider_subscription_id);

ALTER TABLE public.billing_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_read_own_billing_customers"
  ON public.billing_customers FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "users_read_own_billing_subscriptions"
  ON public.billing_subscriptions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "users_read_own_billing_invoices"
  ON public.billing_invoices FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.update_billing_tables_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_customers_updated_at
  BEFORE UPDATE ON public.billing_customers
  FOR EACH ROW EXECUTE FUNCTION public.update_billing_tables_updated_at();

CREATE TRIGGER billing_subscriptions_updated_at
  BEFORE UPDATE ON public.billing_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.update_billing_tables_updated_at();

CREATE TRIGGER billing_invoices_updated_at
  BEFORE UPDATE ON public.billing_invoices
  FOR EACH ROW EXECUTE FUNCTION public.update_billing_tables_updated_at();
