-- 開発者テストコース: フレーズディフェンス コードヴォイシング方式（6課題）
-- Generated by scripts/generate-defense-chord-voicing-dev-migration.mjs
BEGIN;

-- ディフェンス CV II-V-I（オーダー）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order'),
  'defense-dev-cv-iivi-order',
  913,
  'ディフェンス CV II-V-I（オーダー）',
  'Defense CV II-V-I (order)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'order', 'F', 'F', 'F3', true,
  true, 913
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order'), 0, 'Template', NULL, 1, 3, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-phrase-0'), 0, 'Gm7(9)', 1),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-1'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-phrase-0'), 1, 'C7(9.13)', 2),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-2'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-phrase-0'), 2, 'FM7(9)', 3);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-0'), 0, 53, 5, 'F3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-0'), 1, 58, 10, 'Bb3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-0'), 2, 62, 2, 'D4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-0'), 3, 69, 9, 'A4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-1'), 0, 52, 4, 'E3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-1'), 1, 58, 10, 'Bb3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-1'), 2, 62, 2, 'D4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-1'), 3, 69, 9, 'A4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-2'), 0, 52, 4, 'E3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-2'), 1, 57, 9, 'A3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-2'), 2, 60, 0, 'C4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-chord-2'), 3, 67, 7, 'G4', 1, 0, NULL);

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV II-V-I（オーダー）',
  'Defense CV II-V-I (order)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-order'), 'ディフェンス CV II-V-I（オーダー）', 'Defense CV II-V-I (order)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


-- ディフェンス CV II-V-I（ランダム）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random'),
  'defense-dev-cv-iivi-random',
  914,
  'ディフェンス CV II-V-I（ランダム）',
  'Defense CV II-V-I (random)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'random', 'F', 'F', 'F3', true,
  true, 914
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random'), 0, 'Template', NULL, 1, 3, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-phrase-0'), 0, 'Gm7(9)', 1),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-1'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-phrase-0'), 1, 'C7(9.13)', 2),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-2'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-phrase-0'), 2, 'FM7(9)', 3);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-0'), 0, 53, 5, 'F3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-0'), 1, 58, 10, 'Bb3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-0'), 2, 62, 2, 'D4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-0'), 3, 69, 9, 'A4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-1'), 0, 52, 4, 'E3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-1'), 1, 58, 10, 'Bb3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-1'), 2, 62, 2, 'D4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-1'), 3, 69, 9, 'A4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-2'), 0, 52, 4, 'E3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-2'), 1, 57, 9, 'A3', 2, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-2'), 2, 60, 0, 'C4', 1, 0, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-chord-2'), 3, 67, 7, 'G4', 1, 0, NULL);

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV II-V-I（ランダム）',
  'Defense CV II-V-I (random)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-iivi-random'), 'ディフェンス CV II-V-I（ランダム）', 'Defense CV II-V-I (random)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


-- ディフェンス CV テンションリゾルブ（オーダー）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order'),
  'defense-dev-cv-tension-order',
  915,
  'ディフェンス CV テンションリゾルブ（オーダー）',
  'Defense CV tension resolve (order)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'order', 'F', 'F', 'F3', true,
  true, 915
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order'), 0, 'Template', NULL, 1, 3, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-phrase-0'), 0, 'Gm7', 1),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-phrase-0'), 1, 'C7(alt)', 2),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-phrase-0'), 2, 'FM7', 3);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 0, 57, 9, 'A3', 2, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 1, 62, 2, 'D4', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 2, 65, 5, 'F4', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 3, 72, 0, 'C5', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 4, 55, 7, 'G3', 2, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-0'), 5, 70, 10, 'Bb4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 0, 60, 0, 'C4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 1, 64, 4, 'Fb4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 2, 68, 8, 'Ab4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 3, 75, 3, 'Eb5', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 4, 58, 10, 'Bb3', 2, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-1'), 5, 73, 1, 'Db5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 0, 57, 9, 'A3', 2, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 1, 64, 4, 'E4', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 2, 67, 7, 'G4', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 3, 72, 0, 'C5', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 4, 64, 4, 'E4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 5, 69, 9, 'A4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 6, 72, 0, 'C5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 7, 79, 7, 'G5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 8, 62, 2, 'D4', 1, 2, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-chord-2'), 9, 77, 5, 'F5', 1, 2, NULL);

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV テンションリゾルブ（オーダー）',
  'Defense CV tension resolve (order)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-order'), 'ディフェンス CV テンションリゾルブ（オーダー）', 'Defense CV tension resolve (order)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


-- ディフェンス CV テンションリゾルブ（ランダム）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random'),
  'defense-dev-cv-tension-random',
  916,
  'ディフェンス CV テンションリゾルブ（ランダム）',
  'Defense CV tension resolve (random)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'random', 'F', 'F', 'F3', true,
  true, 916
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random'), 0, 'Template', NULL, 1, 3, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-phrase-0'), 0, 'Gm7', 1),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-phrase-0'), 1, 'C7(alt)', 2),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-phrase-0'), 2, 'FM7', 3);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 0, 57, 9, 'A3', 2, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 1, 62, 2, 'D4', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 2, 65, 5, 'F4', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 3, 72, 0, 'C5', 1, 0, 'Gm7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 4, 55, 7, 'G3', 2, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-0'), 5, 70, 10, 'Bb4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 0, 60, 0, 'C4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 1, 64, 4, 'Fb4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 2, 68, 8, 'Ab4', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 3, 75, 3, 'Eb5', 1, 0, 'C7(alt)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 4, 58, 10, 'Bb3', 2, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-1'), 5, 73, 1, 'Db5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 0, 57, 9, 'A3', 2, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 1, 64, 4, 'E4', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 2, 67, 7, 'G4', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 3, 72, 0, 'C5', 1, 0, 'FM7'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 4, 64, 4, 'E4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 5, 69, 9, 'A4', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 6, 72, 0, 'C5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 7, 79, 7, 'G5', 1, 1, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 8, 62, 2, 'D4', 1, 2, NULL),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-chord-2'), 9, 77, 5, 'F5', 1, 2, NULL);

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV テンションリゾルブ（ランダム）',
  'Defense CV tension resolve (random)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-tension-random'), 'ディフェンス CV テンションリゾルブ（ランダム）', 'Defense CV tension resolve (random)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


-- ディフェンス CV 1小節 Dm7+G7（オーダー）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order'),
  'defense-dev-cv-1bar-order',
  917,
  'ディフェンス CV 1小節 Dm7+G7（オーダー）',
  'Defense CV 1-bar Dm7+G7 (order)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'order', 'F', 'F', 'F3', true,
  true, 917
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order'), 0, 'Template', NULL, 1, 1, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-phrase-0'), 0, 'Gm7(9) | C7(9.13)', 1);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 0, 53, 5, 'F3', 2, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 1, 58, 10, 'Bb3', 2, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 2, 62, 2, 'D4', 1, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 3, 69, 9, 'A4', 1, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 4, 52, 4, 'E3', 2, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 5, 58, 10, 'Bb3', 2, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 6, 62, 2, 'D4', 1, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-chord-0'), 7, 69, 9, 'A4', 1, 1, 'C7(9.13)');

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV 1小節 Dm7+G7（オーダー）',
  'Defense CV 1-bar Dm7+G7 (order)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-order'), 'ディフェンス CV 1小節 Dm7+G7（オーダー）', 'Defense CV 1-bar Dm7+G7 (order)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


-- ディフェンス CV 1小節 Dm7+G7（ランダム）
INSERT INTO public.defense_stages (
  id, slug, stage_number, title, title_en, bpm, beats_per_bar, phrase_bars, progression_bars,
  audio_registration_mode, audio_url, staff_layout, attack_trigger, key_fifths,
  required_completion_count, difficulty_level, survive_seconds, player_hp,
  production_staff_hint_mode, production_keyboard_hint_mode,
  play_style, voicing_key_mode, voicing_lowest_key, voicing_start_key,
  voicing_min_lowest_note, play_root_on_chord_change,
  is_active, sort_order
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random'),
  'defense-dev-cv-1bar-random',
  918,
  'ディフェンス CV 1小節 Dm7+G7（ランダム）',
  'Defense CV 1-bar Dm7+G7 (random)',
  100, 4, 1, NULL,
  'single_source', 'https://jazzify-cdn.com/fantasy-bgm/ear-training-self-paced-drum-loop.mp3', 'grand', 'measure', -1,
  1, 3, 120, 20, 'always', 'always',
  'chord_voicing', 'random', 'F', 'F', 'F3', true,
  true, 918
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  stage_number = EXCLUDED.stage_number,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  bpm = EXCLUDED.bpm,
  progression_bars = EXCLUDED.progression_bars,
  audio_registration_mode = EXCLUDED.audio_registration_mode,
  audio_url = EXCLUDED.audio_url,
  staff_layout = EXCLUDED.staff_layout,
  play_style = EXCLUDED.play_style,
  voicing_key_mode = EXCLUDED.voicing_key_mode,
  voicing_lowest_key = EXCLUDED.voicing_lowest_key,
  voicing_start_key = EXCLUDED.voicing_start_key,
  voicing_min_lowest_note = EXCLUDED.voicing_min_lowest_note,
  play_root_on_chord_change = EXCLUDED.play_root_on_chord_change;

DELETE FROM public.defense_phrases WHERE stage_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random');

INSERT INTO public.defense_phrases (
  id, stage_id, order_index, title, audio_url, loop_start_measure, loop_end_measure, key_fifths, required_completion_count
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-phrase-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random'), 0, 'Template', NULL, 1, 1, -1, NULL
);

DELETE FROM public.defense_phrase_chords WHERE phrase_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-phrase-0');

INSERT INTO public.defense_phrase_chords (id, phrase_id, order_index, chord_name, measure_number)
VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-phrase-0'), 0, 'Gm7(9) | C7(9.13)', 1);

INSERT INTO public.defense_phrase_chord_notes (
  chord_id, order_index, pitch_midi, pitch_class, note_name, staff, step_index, staff_chord_name
) VALUES
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 0, 53, 5, 'F3', 2, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 1, 58, 10, 'Bb3', 2, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 2, 62, 2, 'D4', 1, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 3, 69, 9, 'A4', 1, 0, 'Gm7(9)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 4, 52, 4, 'E3', 2, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 5, 58, 10, 'Bb3', 2, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 6, 62, 2, 'D4', 1, 1, 'C7(9.13)'),
  (uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-chord-0'), 7, 69, 9, 'A4', 1, 1, 'C7(9.13)');

INSERT INTO public.lessons (
  id, course_id, title, title_en, description, description_en,
  premium_only, order_index, block_number, block_name, block_name_en, nav_links, assignment_description
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-lesson'),
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test'),
  'ディフェンス CV 1小節 Dm7+G7（ランダム）',
  'Defense CV 1-bar Dm7+G7 (random)',
  'コードヴォイシング方式のディフェンス開発テスト。全12キー移調・音源ループ継続・進行HUD/速度非表示。',
  'Defense chord-voicing dev test: 12-key transposition, continuous loop, no progression HUD or speed control.',
  false,
  (SELECT COALESCE(MAX(order_index), 0) + 1 FROM public.lessons WHERE course_id = uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'course-developer-test')),
  1, 'テスト', 'Test', '["lesson"]'::jsonb, NULL
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en;

INSERT INTO public.lesson_songs (
  id, lesson_id, song_id, order_index, is_clear_required, clear_conditions,
  is_fantasy, is_survival, is_ear_training, is_balloon_rush,
  is_survival_tutorial, is_ear_training_tutorial, is_video_lesson, is_defense,
  defense_stage_id, title, title_en
) VALUES (
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-lsong'), uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random-lesson'), NULL, 0, true, '{"count": 1, "rank": "S"}'::jsonb,
  false, false, false, false, false, false, false, true,
  uuid_generate_v5('a0000000-0000-4000-8000-000000000001'::uuid, 'defense-dev-cv-1bar-random'), 'ディフェンス CV 1小節 Dm7+G7（ランダム）', 'Defense CV 1-bar Dm7+G7 (random)'
)
ON CONFLICT (id) DO UPDATE SET
  defense_stage_id = EXCLUDED.defense_stage_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en;


COMMIT;
