name: Pre-merge Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-all:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run all checks
      run: |
        echo "🔍 Running TypeScript type check..."
        npm run type-check
        
        echo "🔍 Running ESLint..."
        npm run lint
        
        echo "🏗️ Running build..."
        npm run build
        
        echo "✅ All checks passed!"
      env:
        CI: true
    
    - name: Check for TypeScript errors in changed files
      run: |
        # Get list of changed TypeScript files
        CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '\.(ts|tsx)$' || true)
        
        if [ -n "$CHANGED_FILES" ]; then
          echo "Checking changed files:"
          echo "$CHANGED_FILES"
          
          # Run TypeScript compiler on changed files
          npx tsc --noEmit $CHANGED_FILES || exit 1
        else
          echo "No TypeScript files changed"
        fi